// Rewrites the `datasource db` block in prisma/schema.prisma to match the
// DATABASE_URL protocol, so the SAME codebase works with SQLite locally
// (offline, no corporate-network access to a Postgres server) and PostgreSQL
// on Vercel. Run automatically by the `predev` / `prebuild` / `vercel-build`
// npm scripts before `prisma generate`.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

// Load .env.local / .env so DATABASE_URL is available when run standalone.
function loadEnvFile(path) {
  try {
    for (const line of readFileSync(path, "utf8").split("\n")) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/i);
      if (m && !process.env[m[1]]) {
        process.env[m[1]] = m[2].replace(/^["']|["']$/g, "");
      }
    }
  } catch {
    /* file may not exist */
  }
}

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
loadEnvFile(join(root, ".env.local"));
loadEnvFile(join(root, ".env"));

const url = process.env.DATABASE_URL || "file:./dev.db";
const isSqlite = url.startsWith("file:");

const block = isSqlite
  ? `datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}`
  : `datasource db {
  provider  = "postgresql"
  url       = env("DATABASE_URL")
  directUrl = env("DIRECT_URL")
}`;

const schemaPath = join(root, "prisma", "schema.prisma");
const schema = readFileSync(schemaPath, "utf8");
const updated = schema.replace(/datasource db \{[\s\S]*?\n\}/, block);

if (updated !== schema) {
  writeFileSync(schemaPath, updated);
}

// The Prisma CLI only auto-loads `.env` (not `.env.local`), so mirror the DB
// vars there. `.env` is gitignored, so no secret is committed.
const directUrl = process.env.DIRECT_URL || url;
const envLines = [
  "# Auto-generated by scripts/prepare-db.mjs for the Prisma CLI. Do not edit.",
  `DATABASE_URL="${url}"`,
];
if (!isSqlite) envLines.push(`DIRECT_URL="${directUrl}"`);
writeFileSync(join(root, ".env"), envLines.join("\n") + "\n");

console.log(
  `[prepare-db] provider = ${isSqlite ? "sqlite" : "postgresql"}`
);
